DROP DATABASE IF EXISTS sneakers;
CREATE DATABASE IF NOT EXISTS sneakers;

USE sneakers;

SELECT * FROM sales;
SELECT * FROM sales_reprentative;
SELECT * FROM products;
SELECT * FROM customers;
SELECT * FROM suppliers; 

### Objective 1: Analysing sales performance
-- 1. What is the total sales amount generated by each sales representative
SELECT 
sales_reprentative.FirstName, 
sales_reprentative.LastName, 
SUM(sales.TotalAmount) as TotalSales
FROM sales  
JOIN 
sales_reprentative  
ON sales.SalesRepID = sales_reprentative.SalesRepID
GROUP BY
sales_reprentative.SalesRepID, 
sales_reprentative.FirstName, 
sales_reprentative.LastName
ORDER BY
TotalSales DESC
LIMIT 10;

-- Sales by region
SELECT
sales_reprentative.Region, SUM(sales.TotalAmount) as TotalSales
FROM
sales
JOIN 
sales_reprentative
ON sales.SalesRepID = sales_reprentative.SalesRepID
GROUP BY 
sales_reprentative.Region
ORDER BY 
TotalSales DESC;

-- 2. How many products have been sold in each store location
SELECT
sales.StoreLocation, COUNT(sales.ProductID) as Total_products_Sold
FROM 
sales
GROUP BY sales.StoreLocation;

-- 3. Which Product category has the highest total sales amount?
SELECT
products.Category, 
SUM(sales.TotalAmount) as TotalSales
FROM
sales
JOIN
products ON sales.ProductID = products.ProductID
GROUP BY
products.Category
ORDER BY 
TotalSales DESC;

-- 4. What is the average quantity of products sold per sale?
SELECT
AVG(sales.quantity) as avg_quantity_per_sale
FROM 
sales;

-- 5 . Which customer has made the highest number of purchases
SELECT 
customers.FirstName, customers.LastName, COUNT(sales.SaleID) as purchase_count
FROM
sales
JOIN
customers ON sales.CustomerID = customers.CustomerID
GROUP BY
customers.FirstName, 
customers.LastName
ORDER BY 
purchase_count DESC;

-- 6. What is the distribution of total sales amounts across different months?
SELECT 
date_format(Date, '%Y-%m') as Month,
SUM(TotalAmount) as MonthlySales
FROM
sales
GROUP BY Month
ORDER BY Month; 

-- 7. How does sales performance of different regions compare?
SELECT
sales.StoreLocation, SUM(sales.TotalAmount) as total_sales
FROM
sales
GROUP BY
sales.StoreLocation;

-- 8. What is the total sales amount generated for each product?
SELECT
products.ProductName, SUM(TotalAmount) as total_sale
FROM sales
JOIN products ON sales.ProductID = products.ProductID
GROUP BY
products.ProductName;

-- 9. What is the average sales amount per transanction?
SELECT AVG(TotalAmount) as avg_sales_per_transaction
FROM sales;

-- 10. How Many sales transactions were made by each sales Transaction?
SELECT sales_reprentative.FirstName, sales_reprentative.LastName, COUNT(sales.SaleID) as Transaction_count
FROM 
sales
JOIN sales_reprentative ON sales.SalesRepID = sales.SalesRepID
GROUP BY
sales_reprentative.FirstName,
sales_reprentative.LastName; 